### PR TITLE
Run tests with GitHubActions

### PR DESCRIPTION
**Pull request by robertofrontado**
Added job that runs ReccoUITests on every commit when pushed to main or to a PR that targets main

### CODE REVIEW

**Comment by arubio** [comment]
Will this run test on a PR and the after merging that PR it will run them again?

**Comment by robertofrontado** [comment]
> Will this run test on a PR and the after merging that PR it will run them again?

That is correct, which might be a bit overkill for now but its to make sure master never breaks during merges, unless we force a PR to always be up to date, which I think we already do 🤔

**Comment by arubio** [comment]
> > Will this run test on a PR and the after merging that PR it will run them again?
> 
> That is correct, which might be a bit overkill for now but its to make sure master never breaks during merges, unless we force a PR to always be up to date, which I think we already do 🤔

Okay, your choice, I was just thinking about limits on running builds

**Review by arubio — APPROVED** [review]

**Comment by robertofrontado** [comment]
>Okay, your choice, I was just thinking about limits on running builds
Yeah I'll run it only during PRs for now to minimize that, and add develop as a target

**Pull request merged**
